First review
AlexanderNachmanovich/blog-customizer pull request #2
Opened 2024-12-24 10:49 UTC by AlexanderNachmanovich

2024-12-24 12:32 UTC, SergeyK2004 requested changes
Добрый день!  (нужно развернуть комментарий ↓)

У вас получилась отличная работа:
* Полностью реализован функционал.
* Сайдбар закрывается по клику вне сайдбара
* Состояния страницы и формы разделены
* Обработчик события `submit` навешивается на форму, а не на клик по кнопке
* Для условного добавления стилей используется библиотека `clsx`
* Типизированы все пропсы


Но есть пара моментов, который надо поправить:

- За состояние страницы отвечает компонент `App`, а за состояние формы компонент `ArticleParamsForm`. Нужно продумать логику передачи данных от `App` в форму и обратно.
- Компонент страницы не должен знать про состояние формы. Состояние формы надо перенести в компонент `ArticleParamsForm`. Туда же нужно перенести все обработчики.

Правки можно лучше остаются на ваше усмотрение:

- Обычно корневой `index.tsx` держат максимально компактным. Стоит вынести компонент `App` в отдельный файл в папке `components/app/App.tsx`.
- Для одиночных селекторов не стоит использовать библиотеку `clsx` (см. компоненты `Article` и `App`).
- Обработчик клика по оверлею для закрытия сайдбара лучше попробовать реализовать через кастомный хук.

Успешного рефакторинга!

2024-12-24 12:32 UTC, SergeyK2004 commented on src/index.tsx
> +	const toggleSidebar = () => {
Надо исправить:
Компонент страницы не должен знать про состояние формы. Состояние формы надо перенести в компонент `ArticleParamsForm`. Туда же нужно перенести все обработчики.

2024-12-24 12:32 UTC, SergeyK2004 commented on src/components/article-params-form/ArticleParamsForm.tsx
> +	onApply: (newSettings: typeof defaultArticleState) => void;
Надо исправить:
У вас уже описан тип для объекта с настройками 
Посмотрите ArticleStateType в константах

---

Вам необходимо в компонент передать только функцию для изменения стэйта настроек статьи, все остальные пропсы следует убрать

2024-12-24 12:32 UTC, SergeyK2004 commented on src/components/article-params-form/ArticleParamsForm.tsx
> +			fontFamilyOptions.find(option => option.value === value) ||
**Можно лучше:**

Не стоит излишне усложнять обработчик:

```ts
const handleOnChange = (field: keyof ArticleStateType) => {
  return (value: OptionType) => {
	setState((prevState) => ({ ...prevState, [field]: value }));
  };
};
```

тогда его использование будет выглядеть так:

```ts
<Select
  title={'шрифт'}
  onChange={handleOnChange('fontFamilyOption')}
  selected={state.fontFamilyOption}
  options={fontFamilyOptions}
/>
```

2024-12-24 12:32 UTC, SergeyK2004 commented on src/components/article-params-form/ArticleParamsForm.tsx
> +		const panel = document.querySelector(`.${styles.container}`);
Надо исправить:
Не стоит выполнять поиск элементов разметки в Реакте.
Обратите внимание на использование хука ref для работы с разметкой, которую генерирует Реакт

2024-12-24 12:32 UTC, SergeyK2004 commented on src/components/article-params-form/ArticleParamsForm.tsx
> +	useEffect(() => {
**Можно лучше:**

Будет здорово вынести закрытие по клику в оверлей в кастомный хук. Посмотрите, как пример, использование хука в компоненте Select. Только лучше будет использовать событие `mousedown`

2024-12-24 12:32 UTC, SergeyK2004 commented on src/components/article-params-form/ArticleParamsForm.tsx
> +				className={clsx(styles.container, { [styles.container_open]: isOpen })}
**Отлично:**

Здорово, что используете библиотеку `clsx`.

2024-12-24 12:32 UTC, SergeyK2004 commented on src/components/article-params-form/ArticleParamsForm.tsx
> +				<form className={styles.form} onSubmit={handleSubmit}>
**Отлично:**

Отлично, что обработчик сохранения данных вызывается при отправке формы.

2024-12-24 12:32 UTC, SergeyK2004 commented on src/index.tsx
>  const App = () => {
**Можно лучше:**

Обычно корневой `index.tsx` держат максимально компактным. Стоит вынести компонент `App` в отдельный файл в папке `components/app/App.tsx`.

2024-12-25 15:53 UTC, AlexanderNachmanovich commented
Сделал рефакторинг
https://github.com/AlexanderNachmanovich/blog-customizer/pull/2/commits/e1c5e0672bf5dc709df11719c0f166a41aadf060

2024-12-26 02:31 UTC, SergeyK2004 requested changes
Отлично. Здорово, что реализовали закрытие по оверлею через кастомный хук. Но осталось одно замечание про состояние открытости формы. Посмотрите подробности в коде.

2024-12-26 02:31 UTC, SergeyK2004 commented on src/components/app/App.tsx
> +	const [isSidebarOpen, setIsSidebarOpen] = useState(false);
**Надо исправить:**

Состояние открытия формы необходимо создавать и хранить в самой форме. Каждый компонент сам должен отвечать за хранение и обработку своего состояния. Использовать подъем состояния формы в родительский компонент не имеет смысла для нашего приложения.

2024-12-27 00:16 UTC, SergeyK2004 approved these changes
Отлично. Замечаний больше нет.
Ваша работа принята.
Желаю успехов в дальнейшем обучении.

2024-12-27 06:36 UTC, merged